#!/bin/bash

packages='gcc avahi-daemon rsync x11 xorg midori lxde python3 python2 alsa bluez vim sound calender omxplayer c++ hostnamectl lua man perl sensible-editor sensible-browser sensible-pager elect-editor unicode-start unicode-stop'

# Disabling swap
sudo swapoff -a ; cd /var ; sudo dd if=/dev/zero of=/swap bs=1M count=100 ; rm swap ; cd

# Updating the repository
sudo apt-get update ; sudo apt autoremove -y; 

# Removing unncessary packages 
for package in $packages
do
	sudo apt remove --purge $(sudo apt search $package | grep installed | awk '{printf $1}'| sed 's@/[^ ]*@@g') -y ; sudo apt autoremove -y ; 
	sudo apt remove --purge $(sudo dpkg --get-selections | grep -v "deinstall" | grep $package | sed 's/install//') -y ; sudo apt autoremove -y ;
done


# Removing devlopment packages
sudo apt remove --purge $(sudo dpkg --get-selections | grep "\-dev" | sed s/install//) -y ; 


# Removing the test code
sudo rm -rf /opt ; 


# Cleaning apt cache
sudo apt-get clean ; sudo apt clean ; 


# Removing apt cache
sudo rm -rf /var/lib/apt/lists/* ; sudo rm -rf /var/cache/apt/* ;


# Delete the vlogs 
sudo rm -rf /var/log/* ;

# Final image size
df -h
